### ISSUE TITLE
This is not a Reuleaux tetrahedron

### ISSUE THREAD

**Issue by gerw** [NicolasDouillet/meshed_reuleaux_tetrahedron#1]
This package does not produce a Reuleaux tetrahedron.

In this line,

https://github.com/NicolasDouillet/meshed_reuleaux_tetrahedron/blob/a5da9b9ec3791b9b4134c3314246e5b1c29e8df0/meshed_reuleaux_tetrahedron.m#L278

it is somehow assumed that `X == 0`. In fact, one can simply check that the expression

`D = sqrt(sum((V - X).^2,2));`

does not equal `Rho` afterwards.

**Comment by NicolasDouillet** [comment]
Hi gerw and thank you for reporting this issue !

I will check the code and correct it as soon as possible.

Cheers.

Nicolas

**Comment by NicolasDouillet** [comment]
Fixed. This is now a Reuleaux tetrahedron, according to its definition.

**Comment by gerw** [comment]
Yes, I can confirm that it is a Reuleaux tetrahedron now. However, the triangulation is not so nice (try `sample_step=40`), since the region near the edges is not resolved and contains very big (but slim) triangles.
